# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='receivedMessages',
            field=models.ManyToManyField(related_name='received_by', to='mail.Message'),
        ),
    ]
