# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 23:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageID', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=500)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('isDraft', models.BooleanField(default=False)),
                ('attachment', models.ImageField(default=None, upload_to='images')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
